### ISSUE TITLE
AnswerService.post() doesn't work

### ISSUE THREAD

**Issue by romac** [reminisceme/app#38]
When posting the answers, it fails with:

```
I20150511-12:24:54.183(2)? Exception while invoking method 'Answer.post' [object Object]
I20150511-12:24:54.183(2)?     at Object.post (server/services/AnswerService.es6.js:48:26)
I20150511-12:24:54.183(2)?     at [object Object].Meteor.methods.Answer.post (app/server/methods.js:40:28)
I20150511-12:24:54.184(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150511-12:24:54.184(2)?     at packages/ddp/livedata_server.js:648:1
I20150511-12:24:54.184(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150511-12:24:54.184(2)?     at packages/ddp/livedata_server.js:647:1
I20150511-12:24:54.184(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150511-12:24:54.184(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150511-12:24:54.184(2)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by romac** [comment]
Make sure to pull from `master` before checking the issue out.
